//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShop.WebUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class rds_track_change
    {
        public int id { get; set; }
        public Nullable<System.DateTime> executed_at { get; set; }
    }
}
